"""The backtest engine, driven by hand-built option bars.

Every frame here is generated by Black-Scholes at a known volatility, so a
price the engine recovers can be checked against the number that produced it.
Real Alpaca bars have the same columns and the same tz-aware index.
"""

from datetime import date, timedelta
from decimal import Decimal
from functools import lru_cache

import pandas as pd
import pytest

from flywheel.backtest.engine import (
    DISABLED_CHECKS,
    BarPricer,
    Cursor,
    LookaheadError,
    backtest_limits,
    implied_vol,
    run_backtest,
)
from flywheel.backtest.options_history import occ_symbol
from flywheel.domain import SHARES_PER_CONTRACT, Portfolio, ProposedOrder
from flywheel.optimizer.candidates import build_candidates
from flywheel.optimizer.payoff import bs_price
from flywheel.risk.gate import veto
from flywheel.risk.limits import Limits

EXPIRY = date(2024, 6, 21)
VOL = 0.18
STRATEGY = {
    "target_delta": {"calm": {"min": 0.25, "max": 0.35}},
    "dte": {"min": 5, "max": 14},
    "size_multiplier": {"calm": 1.0},
}
LIMITS = Limits(
    max_position_pct=25.0,
    max_deployed_pct=60.0,
    max_drawdown_pct=15.0,
    max_net_delta=150.0,
    max_vega=500.0,
    max_assignment_prob=0.35,
    min_open_interest=500,
    max_spread_pct=5.0,
)


def trading_days(end: date, count: int) -> list[date]:
    """The `count` weekdays ending on `end`, inclusive.

    Counted backwards from the expiry on purpose. Counting forwards from a
    start date leaves the window ending wherever the arithmetic lands, and an
    entry day five to fourteen days before the expiry then does not exist —
    which looks exactly like a strategy that declined to trade.
    """
    days, day = [], end
    while len(days) < count:
        if day.weekday() < 5:
            days.append(day)
        day -= timedelta(days=1)
    return list(reversed(days))


def underlying_frame(days: list[date], closes: list[float]) -> pd.DataFrame:
    index = pd.DatetimeIndex([pd.Timestamp(d) for d in days])
    return pd.DataFrame(
        {
            "close": closes,
            "open": closes,
            "high": closes,
            "low": closes,
            "volume": [1e6] * len(closes),
        },
        index=index,
    )


def option_frame(
    symbol: str,
    expiry: date,
    strikes: list[float],
    days: list[date],
    closes: dict[date, float],
    volume: int = 5000,
    vol: float = VOL,
) -> pd.DataFrame:
    """Bars priced at `vol`, in the shape Alpaca returns them."""
    rows = []
    for day in days:
        if day > expiry:
            continue
        tau = max((expiry - day).days, 0) / 365.0
        for strike in strikes:
            for right in ("P", "C"):
                price = bs_price(closes[day], strike, tau, vol, right)
                if price < 0.05:
                    continue
                rows.append(
                    {
                        "symbol": occ_symbol(symbol, expiry, right, strike),
                        "timestamp": pd.Timestamp(day, tz="UTC"),
                        "open": price,
                        "high": price,
                        "low": price,
                        "close": price,
                        "volume": volume,
                        "trade_count": 100,
                        "vwap": price,
                    }
                )
    return pd.DataFrame(rows).set_index(["symbol", "timestamp"])


STRIKES = [float(s) for s in range(300, 580, 5)]


@lru_cache(maxsize=4)
def _flat_world(spot: float, history: int):
    """A market that does not move, ending on a single monthly expiry.

    Cached because building the chain prices every strike on every day, and
    six tests want the same one.
    """
    days = trading_days(EXPIRY, history)
    closes = dict.fromkeys(days, spot)
    strikes = [s for s in STRIKES if spot * 0.85 <= s <= spot * 1.15]
    bars = underlying_frame(days, [closes[d] for d in days])
    chains = {EXPIRY: option_frame("SPY", EXPIRY, strikes, days, closes)}
    return days, bars, chains


def flat_world(spot: float = 500.0, history: int = 260):
    days, bars, chains = _flat_world(spot, history)
    return list(days), bars.copy(), dict(chains)


# --- the pricer ------------------------------------------------------------


def test_the_pricer_sells_at_the_bid_and_never_at_the_mid():
    """The single rule separating a backtest from a sales pitch.

    There is no historical bid, so one is constructed from the bar close. The
    fill must still be booked at that constructed bid: booking the mid is how
    a wheel backtest invents returns nobody could have captured.
    """
    days, _, chains = flat_world()
    pricer = BarPricer(lambda expiry: chains[expiry], haircut_pct=2.0)
    as_of = max(d for d in days if d < EXPIRY)

    rows = pricer.rows(EXPIRY, as_of)

    assert rows
    row = rows[0]
    assert row["bid"] < row["ask"]
    assert float(row["bid"]) == pytest.approx(float(row["close"]) * 0.98)


def test_a_contract_that_did_not_trade_that_day_is_not_offered():
    """Open interest does not exist historically; a real fill does.

    Substituting volume for open interest would be a fabricated number in a
    field the risk gate reads. Requiring the contract to have actually traded
    is stricter, and it is measured rather than modelled.
    """
    days, _, chains = flat_world()
    silent = chains[EXPIRY].copy()
    silent["volume"] = 0
    pricer = BarPricer(lambda expiry: silent)
    as_of = max(d for d in days if d < EXPIRY)

    assert pricer.rows(EXPIRY, as_of) == []


def test_implied_volatility_is_recovered_from_the_bar_close():
    """The bars carry no IV, so it is solved for. Check it round-trips."""
    price = bs_price(500.0, 480.0, 30 / 365, 0.22, "P")
    assert implied_vol(price, 500.0, 480.0, 30 / 365, "P") == pytest.approx(
        0.22, abs=1e-4
    )


def test_open_interest_is_not_invented():
    """The one check with no historical data is disabled in the open."""
    assert DISABLED_CHECKS == ("min_open_interest",)
    assert backtest_limits(LIMITS).min_open_interest == 0
    assert backtest_limits(LIMITS).max_spread_pct == LIMITS.max_spread_pct


# --- no lookahead ----------------------------------------------------------


def test_the_cursor_refuses_a_reading_from_the_future():
    """Structural, not a convention. Every read goes through here."""
    cursor = Cursor(date(2024, 6, 10))
    cursor.check(date(2024, 6, 10))
    with pytest.raises(LookaheadError):
        cursor.check(date(2024, 6, 11))


def test_the_pricer_never_returns_a_bar_dated_after_the_cursor():
    days, _, chains = flat_world()
    pricer = BarPricer(lambda expiry: chains[expiry])
    as_of = days[-30]
    for row in pricer.rows(EXPIRY, as_of):
        assert row["as_of"] <= as_of


# --- the engine ------------------------------------------------------------


def test_a_flat_market_yields_a_positive_return():
    """The sanity case: nothing moves, every put expires, premium is kept."""
    days, bars, chains = flat_world()
    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    assert result.cycles, "no cycle was opened at all"
    assert result.equity_curve.iloc[-1] > result.equity_curve.iloc[0]
    assert result.cycles[-1].outcome == "expired"


def test_a_thirty_percent_gap_down_produces_assignment_and_a_loss():
    days, bars, chains = flat_world()
    crashed = dict.fromkeys(days, 500.0)
    crashed[EXPIRY] = 350.0
    closes = [crashed[d] for d in days]
    bars = underlying_frame(days, closes)

    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    assert result.cycles[-1].outcome == "assigned"
    assert result.equity_curve.iloc[-1] < result.equity_curve.iloc[0]


def test_the_cycle_count_matches_the_number_of_expiries():
    """One entry per expiry when the wheel keeps returning to cash."""
    expiries = [date(2024, 5, 17), date(2024, 6, 21)]
    spot = 500.0
    days = trading_days(expiries[-1], 300)
    closes = dict.fromkeys(days, spot)
    strikes = [float(s) for s in range(425, 575, 5)]
    bars = underlying_frame(days, [spot] * len(days))
    chains = {e: option_frame("SPY", e, strikes, days, closes) for e in expiries}

    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=expiries,
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    assert len(result.cycles) == len(expiries)


def test_no_recorded_order_ever_violated_a_limit():
    """Re-run the live gate over every fill the engine booked.

    This is the test that proves the backtest and the agent share a risk
    model. If it needs its own copy of `veto` to pass, the claim is false.
    """
    days, bars, chains = flat_world()
    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )
    limits = backtest_limits(LIMITS)

    assert result.cycles
    for cycle in result.cycles:
        order = ProposedOrder(
            symbol=cycle.symbol,
            right=cycle.right,
            strike=cycle.strike,
            expiry=cycle.expiry,
            contracts=-cycle.contracts,
            limit_price=cycle.premium,
            delta=cycle.delta,
            vega=cycle.vega,
            assignment_prob=cycle.assignment_prob,
            open_interest=0,
            spread_pct=cycle.spread_pct,
        )
        portfolio = Portfolio(
            equity=cycle.equity_before,
            cash=cycle.cash_before,
            peak_equity=cycle.equity_before,
            deployed=Decimal("0"),
            wheels={cycle.symbol: cycle.wheel_before},
        )
        assert veto(order, portfolio, limits).approved, cycle.occ_symbol


def test_a_covered_call_is_never_written_below_the_share_basis():
    """The wheel's whole discipline: never lock in a loss on the stock.

    After assignment the basis sits far above the market, so no call in the
    delta band clears it. The correct behaviour is to hold the shares and
    write nothing, not to sell the cheapest call available.
    """
    expiries = [date(2024, 5, 17), date(2024, 6, 21)]
    days = trading_days(expiries[-1], 300)
    closes = dict.fromkeys(days, 500.0)
    for day in days:
        if day >= expiries[0]:  # the crash must land on the expiry, not after it
            closes[day] = 350.0
    strikes = [float(s) for s in range(300, 575, 5)]
    bars = underlying_frame(days, [closes[d] for d in days])
    chains = {e: option_frame("SPY", e, strikes, days, closes) for e in expiries}

    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=expiries,
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    calls = [c for c in result.cycles if c.right == "C"]
    assert calls == []
    assert any("basis" in note for note in result.skipped)


def test_nothing_non_finite_ever_reaches_the_optimizer():
    """A NaN in a loss scenario does not raise; it silently distorts the CVaR.

    Running the suite with RuntimeWarnings as errors turns up noise from
    inside cvxpy's own shape arithmetic, which is not our data. This checks
    the thing that would actually matter — the numbers we hand it.
    """
    import numpy as np

    days, _, chains = flat_world()
    pricer = BarPricer(lambda expiry: chains[expiry])
    as_of = max(d for d in days if (EXPIRY - d).days >= 5)
    spot = 500.0
    rows = []
    for row in pricer.rows(EXPIRY, as_of, "P"):
        tau = (EXPIRY - as_of).days / 365.0
        vol = implied_vol(float(row["close"]), spot, float(row["strike"]), tau, "P")
        if vol is not None:
            rows.append({**row, "implied_vol": vol, "open_interest": 0})

    candidates = build_candidates(
        chain_rows=rows,
        spot=spot,
        symbol="SPY",
        right="P",
        as_of=as_of,
        limits=backtest_limits(LIMITS),
        returns=np.full(250, 0.0),
        target_delta=(0.25, 0.35),
    )

    assert candidates
    for candidate in candidates:
        assert np.isfinite(candidate.losses).all(), candidate.occ_symbol
        assert np.isfinite([candidate.delta, candidate.vega]).all()
        assert 0.0 <= candidate.assignment_prob <= 1.0


def test_the_result_records_what_was_modelled():
    """A reader must not have to read the source to learn what is assumed."""
    days, bars, chains = flat_world()
    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry], haircut_pct=2.0),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    assert result.params["haircut_pct"] == 2.0
    assert result.params["disabled_checks"] == list(DISABLED_CHECKS)
    assert result.params["priced_from"] == "daily bars, not quotes"


def test_the_equity_curve_covers_every_trading_day_in_the_window():
    days, bars, chains = flat_world()
    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry]),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    assert len(result.equity_curve) == len(days)
    assert result.equity_curve.index[0] == pd.Timestamp(days[0])


def test_premium_is_booked_at_the_bid_not_the_mid():
    """End to end: the cash the engine credits comes from the haircut price."""
    days, bars, chains = flat_world()
    result = run_backtest(
        symbol="SPY",
        bars=bars,
        pricer=BarPricer(lambda expiry: chains[expiry], haircut_pct=2.0),
        expiries=[EXPIRY],
        limits=LIMITS,
        strategy=STRATEGY,
        initial_capital=Decimal("1000000"),
    )

    cycle = result.cycles[0]
    assert cycle.premium < cycle.mid
    assert float(cycle.premium) == pytest.approx(float(cycle.mid) * 0.98, rel=1e-6)
    assert cycle.proceeds == cycle.premium * cycle.contracts * SHARES_PER_CONTRACT
